"""Small helpers for ADI sphere textures.

The texture is equirectangular:
    x = longitude, y = latitude

For marks that should keep the same apparent size on the sphere, use the
surface_* helpers. They scale x by sec(latitude), undoing the sphere's
cos(latitude) longitude compression.
"""

from __future__ import annotations

import argparse
import math
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable
from xml.sax.saxutils import escape


DEFAULT_WIDTH = 4096
DEFAULT_HEIGHT = 2048
DEFAULT_PNG_WIDTH = 2048
DEFAULT_PNG_HEIGHT = 1024
REPO_ROOT = Path(__file__).resolve().parents[3]


@dataclass
class Texture:
    # SVG output is accumulated as plain lines on purpose. This keeps the helper
    # predictable and lets recipes drop in raw SVG whenever that is clearer.
    width: int = DEFAULT_WIDTH
    height: int = DEFAULT_HEIGHT
    lines: list[str] = field(default_factory=list)


def repo_path(*parts: str) -> Path:
    return REPO_ROOT.joinpath(*parts)


def n(value: float | int) -> str:
    # Keep generated SVG stable and readable; sub-pixel precision is enough for
    # a texture that is later rasterized to PNG.
    if isinstance(value, int):
        return str(value)
    return f"{value:.3f}"


def attrs(**values: object) -> str:
    # Python identifiers use underscores, SVG attributes use dashes. The
    # class_name spelling avoids the reserved word "class".
    out = []
    for key, value in values.items():
        if value is None:
            continue
        if key == "class_name":
            key = "class"
        key = key.replace("_", "-")
        if isinstance(value, float):
            value = n(value)
        out.append(f'{key}="{escape(str(value))}"')
    return (" " + " ".join(out)) if out else ""


def add(tex: Texture, line: str = "") -> None:
    tex.lines.append(line)


def block(tex: Texture, text: str, indent: int = 2) -> None:
    # Raw SVG blocks are the simplest way to author gradients, patterns, icons,
    # or custom art without turning this helper into an SVG framework.
    prefix = " " * indent
    for line in text.strip("\n").splitlines():
        add(tex, prefix + line if line.strip() else "")


def begin(tex: Texture, generator: str, note: str | None = None) -> None:
    add(tex, '<?xml version="1.0" encoding="UTF-8"?>')
    add(tex, f"<!-- Generated by {generator}. -->")
    if note:
        add(tex, f"<!-- {note} -->")
    add(tex, f'<svg width="{tex.width}" height="{tex.height}" viewBox="0 0 {tex.width} {tex.height}" xmlns="http://www.w3.org/2000/svg">')


def end(tex: Texture) -> None:
    add(tex, "</svg>")


def lon_x(tex: Texture, lon: float) -> float:
    # Equirectangular map: -180..180 longitude becomes 0..width. Keep +180 on
    # the right edge instead of wrapping it to the left edge; both points are
    # the same seam on the sphere, but SVG authors expect the right-edge line
    # when they ask for +180.
    x = (lon + 180.0) % 360.0
    if x == 0.0 and lon > 0.0:
        x = 360.0
    return x / 360.0 * tex.width


def lat_y(tex: Texture, lat: float) -> float:
    # SVG y grows downward, so +90 latitude is the top of the image.
    return (90.0 - lat) / 180.0 * tex.height


def x_lon(tex: Texture, x: float) -> float:
    return x / tex.width * 360.0 - 180.0


def y_lat(tex: Texture, y: float) -> float:
    return 90.0 - y / tex.height * 180.0


def sec_lat(lat: float) -> float:
    # A sphere squeezes longitude by cos(latitude). Pre-scaling by sec(latitude)
    # makes labels and short marks keep roughly the same apparent size when the
    # flat texture is wrapped onto the ADI ball. Clamp near the poles so a
    # caller cannot accidentally generate enormous SVG objects.
    clamped = max(-84.0, min(84.0, lat))
    return 1.0 / max(0.08, math.cos(math.radians(clamped)))


def rect(tex: Texture, x: float, y: float, w: float, h: float, **style: object) -> None:
    add(tex, f'  <rect x="{n(x)}" y="{n(y)}" width="{n(w)}" height="{n(h)}"{attrs(**style)}/>')


def line(tex: Texture, x1: float, y1: float, x2: float, y2: float, **style: object) -> None:
    add(tex, f'  <line x1="{n(x1)}" y1="{n(y1)}" x2="{n(x2)}" y2="{n(y2)}"{attrs(**style)}/>')


def ellipse(tex: Texture, cx: float, cy: float, rx: float, ry: float, **style: object) -> None:
    add(tex, f'  <ellipse cx="{n(cx)}" cy="{n(cy)}" rx="{n(rx)}" ry="{n(ry)}"{attrs(**style)}/>')


def circle(tex: Texture, cx: float, cy: float, r: float, **style: object) -> None:
    add(tex, f'  <circle cx="{n(cx)}" cy="{n(cy)}" r="{n(r)}"{attrs(**style)}/>')


def text(tex: Texture, x: float, y: float, value: str, size: float, fill: str, **style: object) -> None:
    add(
        tex,
        f'  <text x="{n(x)}" y="{n(y)}" text-anchor="middle" dominant-baseline="middle" '
        f'font-size="{n(size)}" fill="{fill}"{attrs(**style)}>{escape(value)}</text>',
    )


def surface_block(tex: Texture, lon: float, lat: float, svg: str, class_name: str | None = None) -> None:
    # Surface coordinates are local: (0, 0) is the requested lon/lat point.
    # The inserted block is widened in X before rasterization so it appears
    # normal-sized after sphere projection.
    add(tex, f'    <g{attrs(class_name=class_name)} transform="translate({n(lon_x(tex, lon))} {n(lat_y(tex, lat))}) scale({sec_lat(lat):.6f} 1)">')
    block(tex, svg, indent=6)
    add(tex, "    </g>")


def surface_text(
    tex: Texture,
    lon: float,
    lat: float,
    value: str,
    size: float,
    fill: str,
    x: float = 0,
    y: float = 0,
    opacity: float = 1,
    weight: int = 700,
    class_name: str | None = None,
) -> None:
    surface_block(
        tex,
        lon,
        lat,
        f'<text x="{n(x)}" y="{n(y)}" text-anchor="middle" dominant-baseline="middle" '
        f'font-size="{n(size)}" font-weight="{weight}" fill="{fill}" opacity="{n(opacity)}">{escape(value)}</text>',
        class_name=class_name,
    )


def surface_hline(
    tex: Texture,
    lon: float,
    lat: float,
    x1: float,
    x2: float,
    stroke: str | None = None,
    width: float | None = None,
    opacity: float | None = None,
    class_name: str | None = None,
) -> None:
    surface_block(
        tex,
        lon,
        lat,
        f'<line x1="{n(x1)}" y1="0" x2="{n(x2)}" y2="0"{attrs(class_name=class_name, stroke=stroke, stroke_width=width, opacity=opacity, stroke_linecap="round")}/>',
    )


def surface_vline(
    tex: Texture,
    lon: float,
    lat: float,
    x: float,
    y1: float,
    y2: float,
    stroke: str,
    width: float,
    opacity: float = 1,
) -> None:
    surface_block(
        tex,
        lon,
        lat,
        f'<line x1="{n(x)}" y1="{n(y1)}" x2="{n(x)}" y2="{n(y2)}" stroke="{stroke}" stroke-width="{n(width)}" opacity="{n(opacity)}" stroke-linecap="round"/>',
    )


def surface_ellipse(tex: Texture, lon: float, lat: float, rx: float, ry: float, fill: str, opacity: float = 1) -> None:
    surface_block(tex, lon, lat, f'<ellipse cx="0" cy="0" rx="{n(rx)}" ry="{n(ry)}" fill="{fill}" opacity="{n(opacity)}"/>')


def surface_canvas_hline(tex: Texture, x1: float, y: float, x2: float, class_name: str | None = None) -> None:
    # Convenience for adapting an old flat-SVG horizontal line into a
    # surface-corrected line without manually converting x/y to lon/lat.
    center_x = (x1 + x2) * 0.5
    surface_hline(tex, x_lon(tex, center_x), y_lat(tex, y), x1 - center_x, x2 - center_x, class_name=class_name)


def surface_label_grid(
    tex: Texture,
    lons: Iterable[float],
    lats: Iterable[float],
    size: float,
    fill: str,
    opacity: float = 1,
    class_name: str | None = None,
) -> None:
    for lat in lats:
        for lon in lons:
            surface_text(tex, lon, lat, f"{lon:g}", size, fill, opacity=opacity, class_name=class_name)


def svg_text(tex: Texture) -> str:
    return "\n".join(tex.lines) + "\n"


def write_svg(tex: Texture, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(svg_text(tex), encoding="utf-8")


def export_png(svg_path: Path, png_path: Path, width: int, height: int) -> None:
    # Inkscape is used only as an SVG rasterizer. The SVG remains the editable
    # source; the PNG is what the sample loads at runtime.
    inkscape = shutil.which("inkscape")
    if not inkscape:
        raise RuntimeError("inkscape was not found; SVG was generated but PNG export is unavailable")
    png_path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            inkscape,
            str(svg_path),
            "--export-type=png",
            f"--export-filename={png_path}",
            f"--export-width={width}",
            f"--export-height={height}",
        ],
        check=True,
    )


def add_output_args(parser: argparse.ArgumentParser, default_svg: Path, default_png: Path) -> None:
    parser.add_argument("--svg", type=Path, default=default_svg)
    parser.add_argument("--png", type=Path, default=default_png)
    parser.add_argument("--width", type=int, default=DEFAULT_WIDTH)
    parser.add_argument("--height", type=int, default=DEFAULT_HEIGHT)
    parser.add_argument("--png-width", type=int, default=DEFAULT_PNG_WIDTH)
    parser.add_argument("--png-height", type=int, default=DEFAULT_PNG_HEIGHT)
    parser.add_argument("--no-png", action="store_true")


def write_outputs(tex: Texture, args: argparse.Namespace) -> None:
    write_svg(tex, args.svg)
    if not args.no_png:
        export_png(args.svg, args.png, args.png_width, args.png_height)
