#!/usr/bin/python

import sys, os, platform

argstr = ''

for arg in sys.argv[1:]:
	argstr += ' ' + arg

mydir = os.path.dirname(os.path.abspath(__file__))

ostype = os.getenv('OSTYPE')
if (ostype == None):
    ostype = platform.system().lower()

machtype = os.getenv('MACHTYPE')
if (machtype == None):
    machtype = platform.machine()

if (ostype == 'darwin'):
    osspec = 'MacOS'
else:
    osspec = ostype + '_' + machtype

appcmd = mydir + '/' + osspec + '/dcapp_genheader'

if os.path.isfile(appcmd): os.system(appcmd + argstr)
