#!/bin/bash

usage()
{
    cat <<EOF
Usage: $0 [OPTION]...
Get package compilation and linking information.

Options:
    --version      software version
    --prefix       install location
    --exepath      path(s) to add to the PATH environment variable
    --cflags       required compilation flags
    --libs         required linking flags
    --compdepends  makefile compilation dependencies
    --linkdepends  makefile linking dependencies
    --s_overrides  Trick S_overrides file
    --ostype       operating system name
    --machtype     machine hardware name
    --osspec       default directory name extension
    --objdir       default directory name for compiled objects
    --libdir       default directory name for compiled libraries
    --bindir       default directory name for compiled binaries
EOF
    exit $1
}

if test $# -eq 0 ; then
    usage 1 1>&2
fi

CDPATH=""

# find the true path to the script, even if it's a link
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
    DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null && pwd)"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
scriptdir="$(cd -P "$(dirname "$SOURCE")" >/dev/null && pwd)"

mydir="$(cd "$scriptdir/../.."; pwd)"
ostype=`uname -s | tr '[:upper:]' '[:lower:]'`
machtype=`uname -m`
if test "$ostype" = "darwin" ; then
    osspec="MacOS"
else
    osspec="${ostype}_${machtype}"
fi
objdir="obj_${osspec}"
libdir="lib_${osspec}"
bindir="bin_${osspec}"

while test $# -gt 0 ; do
    case $1 in
        --prefix)
            echo $mydir
            ;;
        --osspec)
            echo $osspec
            ;;
        --objdir)
            echo $objdir
            ;;
        --libdir)
            echo $libdir
            ;;
        --bindir)
            echo $bindir
            ;;
##### These are the only lines that should differ from package to package. #####
        --ostype)
            echo $ostype
            ;;
        --machtype)
            echo $machtype
            ;;
        --version)
            echo "1.0.0 alpha"
            ;;
        --exepath)
            echo "${mydir}/dcapp.app/Contents:${mydir}/packages/PixelStream/samples/${bindir}"
            ;;            
        --cflags)
            ;;
        --libs)
            ;;
        --compdepends)
            ;;
        --linkdepends)
            ;;
        --s_overrides)
            echo "${mydir}/3rdParty/trick/makefiles/core.mk"
            ;;            
################################################################################
        *)
            usage 1 1>&2
            ;;
    esac
    shift
done
