#ifndef _DC_APP_LOOKUP_
#define _DC_APP_LOOKUP_

// TODO hate this file, restructure somehow
typedef enum _DcAppAlignType {
    DC_APP_ALIGN_TYPE_UNDEFINED,
    DC_APP_ALIGN_TYPE_LEFT,
    DC_APP_ALIGN_TYPE_CENTER,
    DC_APP_ALIGN_TYPE_RIGHT,
    DC_APP_ALIGN_TYPE_BOTTOM,
    DC_APP_ALIGN_TYPE_MIDDLE,
    DC_APP_ALIGN_TYPE_TOP,
} DcAppAlignType;

typedef enum _DcAppConditionalType {
    DC_APP_CONDITIONAL_TYPE_UNDEFINED,
    DC_APP_CONDITIONAL_TYPE_TRUE,
    DC_APP_CONDITIONAL_TYPE_FALSE,
    DC_APP_CONDITIONAL_TYPE_EQ,
    DC_APP_CONDITIONAL_TYPE_NE,
    DC_APP_CONDITIONAL_TYPE_LT,
    DC_APP_CONDITIONAL_TYPE_GT,
    DC_APP_CONDITIONAL_TYPE_LTE,
    DC_APP_CONDITIONAL_TYPE_GTE,
} DcAppConditionalType;

typedef enum _DcAppSetType {
    DC_APP_SET_TYPE_UNDEFINED,
    DC_APP_SET_TYPE_EQUAL,
    DC_APP_SET_TYPE_ADD,
    DC_APP_SET_TYPE_SUBTRACT,
    DC_APP_SET_TYPE_MULTIPLY,
    DC_APP_SET_TYPE_DIVIDE,
} DcAppSetType;

#endif