.PHONY: all clean

all:
	${MAKE} -C functions
	${MAKE} -C mask
	${MAKE} -C ptz
	${MAKE} -C screensaver

clean:
	${MAKE} -C functions clean
	${MAKE} -C mask clean
	${MAKE} -C ptz clean
	${MAKE} -C screensaver clean
