#ifndef DC_APP_DRAW_TYPES_H
#define DC_APP_DRAW_TYPES_H

typedef enum DcAppDrawAlignmentType {
    DC_APP_DRAW_ALIGNMENT_TYPE_UNDEFINED,
    DC_APP_DRAW_ALIGNMENT_TYPE_LEFT,
    DC_APP_DRAW_ALIGNMENT_TYPE_CENTER,
    DC_APP_DRAW_ALIGNMENT_TYPE_RIGHT,
    DC_APP_DRAW_ALIGNMENT_TYPE_BOTTOM,
    DC_APP_DRAW_ALIGNMENT_TYPE_MIDDLE,
    DC_APP_DRAW_ALIGNMENT_TYPE_TOP,
} DcAppDrawAlignmentType;

#endif
