#ifndef DC_APP_DRAW_TYPES_H
#define DC_APP_DRAW_TYPES_H

typedef enum DcAppAlignType {
    DC_APP_ALIGN_TYPE_UNDEFINED,
    DC_APP_ALIGN_TYPE_LEFT,
    DC_APP_ALIGN_TYPE_CENTER,
    DC_APP_ALIGN_TYPE_RIGHT,
    DC_APP_ALIGN_TYPE_BOTTOM,
    DC_APP_ALIGN_TYPE_MIDDLE,
    DC_APP_ALIGN_TYPE_TOP,
} DcAppAlignType;

#endif
