#ifndef DC_APP_NODE_TYPES_H
#define DC_APP_NODE_TYPES_H

typedef int DcAppNodeIndex;

enum {
    NODE_INDEX_UNDEFINED = 0,
    NODE_FIRST_INDEX = 1,
};

typedef enum DcAppNodeType {
    NODE_TYPE_UNDEFINED,
    NODE_TYPE_ARC,
    NODE_TYPE_BLINK,
    NODE_TYPE_BUTTON,
    NODE_TYPE_CONTAINER,
    NODE_TYPE_ELLIPSE,
    NODE_TYPE_CONDITIONAL,
    NODE_TYPE_DRAW_FUNCTION,
    NODE_TYPE_FUNCTION,
    NODE_TYPE_IMAGE,
    NODE_TYPE_LINE,
    NODE_TYPE_MOUSE_MOTION,
    NODE_TYPE_PANEL,
    NODE_TYPE_PIXELSTREAM,
    NODE_TYPE_POLYGON,
    NODE_TYPE_RECTANGLE,
    NODE_TYPE_SET,
    NODE_TYPE_SPHERE,
    NODE_TYPE_STENCIL,
    NODE_TYPE_PLANET_BREADCRUMBS,
    NODE_TYPE_PLANET_CONTAINER,
    NODE_TYPE_PLANET_ELLIPSE,
    NODE_TYPE_PLANET_IMAGE,
    NODE_TYPE_PLANET_LINE,
    NODE_TYPE_PLANET_POLYGON,
    NODE_TYPE_PLANET_SPHERE,
    NODE_TYPE_PLANET_TEXT,
    NODE_TYPE_PLANET_VIEW,
    NODE_TYPE_TEXT,
    NODE_TYPE_WINDOW,

    // state-conditional container nodes (check parent's state_flags)
    NODE_TYPE_STATE_BUTTON_ENABLED,
    NODE_TYPE_STATE_BUTTON_DISABLED,
    NODE_TYPE_STATE_BUTTON_INDICATOR_ON,
    NODE_TYPE_STATE_BUTTON_INDICATOR_OFF,
    NODE_TYPE_STATE_BUTTON_TRANSITION,
    NODE_TYPE_STATE_MOUSE_PRESSED,
    NODE_TYPE_STATE_MOUSE_RELEASED,
    NODE_TYPE_STATE_MOUSE_ACTIVE,
    NODE_TYPE_STATE_MOUSE_INACTIVE,
    NODE_TYPE_STATE_MOUSE_HOVERED,
    NODE_TYPE_STATE_IF_TRUE,
    NODE_TYPE_STATE_IF_FALSE,

    NODE_TYPE__COUNT,
    NODE_TYPE__MAX = NODE_TYPE__COUNT - 1,
} DcAppNodeType;

// State flags that parents set for conditional child nodes to check
typedef enum DcAppNodeStateFlags {
    NODE_STATE_FLAG_NONE = 0,
    NODE_STATE_FLAG_ENABLED = 1 << 0,
    NODE_STATE_FLAG_INDICATOR_ON = 1 << 1,
    NODE_STATE_FLAG_TRANSITIONING = 1 << 2,
    NODE_STATE_FLAG_PRESSED = 1 << 3,
    NODE_STATE_FLAG_ACTIVE = 1 << 4,
    NODE_STATE_FLAG_HOVERED = 1 << 5,
    NODE_STATE_FLAG_RELEASED = 1 << 6,
    NODE_STATE_FLAG_TRUE = 1 << 7,
    NODE_STATE_FLAG_FALSE = 1 << 8,
} DcAppNodeStateFlags;

// Config flags set at parse time (never change at runtime)
typedef enum DcAppNodeConfigFlags {
    NODE_CONFIG_FLAG_NONE = 0,
    NODE_CONFIG_FLAG_FILL_ENABLED = 1 << 0,
    NODE_CONFIG_FLAG_LINE_ENABLED = 1 << 1,
    NODE_CONFIG_FLAG_HAS_MOUSE_HANDLERS = 1 << 2,
    NODE_CONFIG_FLAG_BACKGROUND_ENABLED = 1 << 3,
} DcAppNodeConfigFlags;

typedef enum DcAppButtonType {
    DC_APP_BUTTON_TYPE_UNDEFINED,
    DC_APP_BUTTON_TYPE_MOMENTARY,
    DC_APP_BUTTON_TYPE_STANDARD,
    DC_APP_BUTTON_TYPE_TOGGLE,
} DcAppButtonType;

typedef enum DcAppConditionalType {
    DC_APP_CONDITIONAL_TYPE_UNDEFINED,
    DC_APP_CONDITIONAL_TYPE_TRUE,
    DC_APP_CONDITIONAL_TYPE_FALSE,
    DC_APP_CONDITIONAL_TYPE_EQ,
    DC_APP_CONDITIONAL_TYPE_NE,
    DC_APP_CONDITIONAL_TYPE_LT,
    DC_APP_CONDITIONAL_TYPE_GT,
    DC_APP_CONDITIONAL_TYPE_LTE,
    DC_APP_CONDITIONAL_TYPE_GTE,
} DcAppConditionalType;

typedef enum DcAppSetType {
    DC_APP_SET_TYPE_UNDEFINED,
    DC_APP_SET_TYPE_EQUAL,
    DC_APP_SET_TYPE_ADD,
    DC_APP_SET_TYPE_SUBTRACT,
    DC_APP_SET_TYPE_MULTIPLY,
    DC_APP_SET_TYPE_DIVIDE,
    DC_APP_SET_TYPE_MIN,
    DC_APP_SET_TYPE_MAX,
    DC_APP_SET_TYPE_PUSH,
    DC_APP_SET_TYPE_POP,
    DC_APP_SET_TYPE_NEGATE,
    DC_APP_SET_TYPE_RECIPROCAL,
    DC_APP_SET_TYPE_ABSOLUTE,
    DC_APP_SET_TYPE_SQUARE,
    DC_APP_SET_TYPE_SQRT,
    DC_APP_SET_TYPE_MODULO,
    DC_APP_SET_TYPE_POWER,
    DC_APP_SET_TYPE_LOG,
    DC_APP_SET_TYPE_EXP,
    DC_APP_SET_TYPE_ROUND,
    DC_APP_SET_TYPE_SIGN,
} DcAppSetType;

typedef enum DcAppStencilChildType {
    STENCIL_CHILD_TYPE_UNDEFINED,
    STENCIL_CHILD_TYPE_ADD,
    STENCIL_CHILD_TYPE_REMOVE,
    STENCIL_CHILD_TYPE_DRAW,
} DcAppStencilChildType;

#endif
