#ifndef DC_APP_PLANET_TYPES_H
#define DC_APP_PLANET_TYPES_H

typedef enum DcAppPlanetCrs {
    DC_APP_PLANET_CRS_UNDEFINED,
    DC_APP_PLANET_CRS_GEODETIC,
    DC_APP_PLANET_CRS_CARTESIAN,
} DcAppPlanetCrs;

typedef enum DcAppPlanetAttitudeFrame {
    DC_APP_PLANET_ATTITUDE_FRAME_UNDEFINED,
    DC_APP_PLANET_ATTITUDE_FRAME_LOCAL_NED,
    DC_APP_PLANET_ATTITUDE_FRAME_CARTESIAN_RPY,
} DcAppPlanetAttitudeFrame;

typedef enum DcAppPlanetViewFlags {
    DC_APP_PLANET_VIEW_FLAGS_NONE = 0,
    DC_APP_PLANET_VIEW_FLAGS_WIREFRAME = 1 << 0,
    DC_APP_PLANET_VIEW_FLAGS_SHOW_LEVELS = 1 << 1,
    DC_APP_PLANET_VIEW_FLAGS_SHOW_ORIGIN = 1 << 2,
    DC_APP_PLANET_VIEW_FLAGS_SHOW_CHUNKS = 1 << 3,
    DC_APP_PLANET_VIEW_FLAGS_FLATTEN = 1 << 4,
} DcAppPlanetViewFlags;

typedef enum DcAppPlanetGeojsonStyleFlags {
    DC_APP_PLANET_GEOJSON_STYLE_FLAGS_NONE = 0,
    DC_APP_PLANET_GEOJSON_STYLE_FLAGS_LINE_COLOR = 1 << 0,
    DC_APP_PLANET_GEOJSON_STYLE_FLAGS_FILL_COLOR = 1 << 1,
    DC_APP_PLANET_GEOJSON_STYLE_FLAGS_LINE_WIDTH = 1 << 2,
} DcAppPlanetGeojsonStyleFlags;

#endif
