#ifndef DC_APP_VALUE_TYPES_H
#define DC_APP_VALUE_TYPES_H

typedef enum DcAppValueType {
    DC_APP_VALUE_TYPE_UNDEFINED,
    DC_APP_VALUE_TYPE_STRING,
    DC_APP_VALUE_TYPE_INTEGER,
    DC_APP_VALUE_TYPE_DOUBLE,
    DC_APP_VALUE_TYPE_BOOLEAN,
} DcAppValueType;

#endif
