
:: Project: samples
:: Auto Generated by:
:: "pl_build.py" version: 1.2.1

:: Project: samples

:: ################################################################################
:: #                              Development Setup                               #
:: ################################################################################

:: keep environment variables modifications local
@setlocal

:: make script directory CWD
@pushd %~dp0
@set dir=%~dp0

:: modify PATH to find vcvarsall.bat
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2019/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build;%PATH%

:: setup environment for MSVC dev tools
@call vcvarsall.bat amd64 > nul

:: default compilation result
@set PL_RESULT=[1m[92mSuccessful.[0m

:: default configuration
@set PL_CONFIG=release

:: check command line args for configuration
:CheckConfiguration
@if "%~1"=="-c" (@set PL_CONFIG=%2) & @shift & @shift & @goto CheckConfiguration
@if "%PL_CONFIG%" equ "release" ( goto release )
@if "%PL_CONFIG%" equ "debug" ( goto debug )

:: ################################################################################
:: #                           configuration | release                            #
:: ################################################################################

:release

:: create output directories
@if not exist "../samples/test/logic" @mkdir "../samples/test/logic"

:: create lock file(s)
@echo LOCKING > "../samples/test/logic/lock.tmp"

@if exist "../samples/test/logic/logic.dll" del "..\samples\test\logic\logic.dll"
@if exist "../samples/test/logic/logic_*.pdb" del "..\samples\test\logic\logic_*.pdb"

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ test | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../pilotlight/out/dcapp-genheader.exe ../samples/test/test.xml

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no 
@set PL_SOURCES="../samples/test/logic/logic.cpp" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: test[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../samples/test/logic/logic.dll" -Fo"../samples/test/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../samples/test/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_test

@del "..\samples\test\logic\*.obj"  > nul 2> nul

:Cleanuprelease

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\samples\test\logic\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../samples/test/logic/lock.tmp" del "..\samples\test\logic\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of release configuration
goto ExitLabel

:: ################################################################################
:: #                            configuration | debug                             #
:: ################################################################################

:debug

:: create output directories
@if not exist "../samples/test/logic" @mkdir "../samples/test/logic"

:: create lock file(s)
@echo LOCKING > "../samples/test/logic/lock.tmp"

@if exist "../samples/test/logic/logic.dll" del "..\samples\test\logic\logic.dll"
@if exist "../samples/test/logic/logic_*.pdb" del "..\samples\test\logic\logic_*.pdb"

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ test | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../pilotlight/out/dcapp-genheader.exe ../samples/test/test.xml

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no 
@set PL_SOURCES="../samples/test/logic/logic.cpp" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: test[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../samples/test/logic/logic.dll" -Fo"../samples/test/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../samples/test/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_test

@del "..\samples\test\logic\*.obj"  > nul 2> nul

:Cleanupdebug

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\samples\test\logic\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../samples/test/logic/lock.tmp" del "..\samples\test\logic\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of debug configuration
goto ExitLabel

:ExitLabel

:: return CWD to previous CWD
@popd
