
:: Project: samples
:: Auto Generated by:
:: "pl_build.py" version: 1.3.0

:: Project: samples

:: ################################################################################
:: #                              Development Setup                               #
:: ################################################################################

:: keep environment variables modifications local
@setlocal

:: make script directory CWD
@pushd %~dp0
@set dir=%~dp0

:: modify PATH to find vcvarsall.bat
@if exist "C:/Program Files/Microsoft Visual Studio/18/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/18/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\18\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/18/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/18/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\18\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/18/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%

:: setup environment for MSVC dev tools
@call vcvarsall.bat amd64 > nul

:: default compilation result
@set PL_RESULT=[1m[92mSuccessful.[0m

:: default configuration
@set PL_CONFIG=release

:: check command line args for configuration
:CheckConfiguration
@if "%~1"=="-c" (@set PL_CONFIG=%2) & @shift & @shift & @goto CheckConfiguration
@if "%PL_CONFIG%" equ "release" ( goto release )
@if "%PL_CONFIG%" equ "debug" ( goto debug )

:: ################################################################################
:: #                           configuration | release                            #
:: ################################################################################

:release

:: create output directories
@if not exist "../samples/mask/logic" @mkdir "../samples/mask/logic"

@if not exist "../samples/screensaver/logic" @mkdir "../samples/screensaver/logic"

@if not exist "../samples/ptz/logic" @mkdir "../samples/ptz/logic"

@if not exist "../samples/lissajous/logic" @mkdir "../samples/lissajous/logic"

:: create lock file(s)
@echo LOCKING > "../samples/lissajous/logic/lock.tmp"

@if exist "../samples/mask/logic/logic.dll" del "..\samples\mask\logic\logic.dll"
@if exist "../samples/mask/logic/logic_*.pdb" del "..\samples\mask\logic\logic_*.pdb"
@if exist "../samples/ptz/logic/logic.dll" del "..\samples\ptz\logic\logic.dll"
@if exist "../samples/ptz/logic/logic_*.pdb" del "..\samples\ptz\logic\logic_*.pdb"
@if exist "../samples/screensaver/logic/logic.dll" del "..\samples\screensaver\logic\logic.dll"
@if exist "../samples/screensaver/logic/logic_*.pdb" del "..\samples\screensaver\logic\logic_*.pdb"
@if exist "../samples/lissajous/logic/logic.dll" del "..\samples\lissajous\logic\logic.dll"
@if exist "../samples/lissajous/logic/logic_*.pdb" del "..\samples\lissajous\logic\logic_*.pdb"

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ mask | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../pilotlight/out/dcapp-genheader.exe ../samples/mask/mask.xml

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no 
@set PL_SOURCES="../samples/mask/logic/logic.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: mask[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../samples/mask/logic/logic.dll" -Fo"../samples/mask/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../samples/mask/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_mask

@del "..\samples\mask\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ptz | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../pilotlight/out/dcapp-genheader.exe ../samples/ptz/ptz.xml

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no 
@set PL_SOURCES="../samples/ptz/logic/logic.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: ptz[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../samples/ptz/logic/logic.dll" -Fo"../samples/ptz/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../samples/ptz/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_ptz

@del "..\samples\ptz\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~ screensaver | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../pilotlight/out/dcapp-genheader.exe ../samples/screensaver/screensaver.xml

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no 
@set PL_SOURCES="../samples/screensaver/logic/logic.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: screensaver[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../samples/screensaver/logic/logic.dll" -Fo"../samples/screensaver/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../samples/screensaver/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_screensaver

@del "..\samples\screensaver\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ lissajous | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../pilotlight/out/dcapp-genheader.exe ../samples/lissajous/lissajous.xml

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no 
@set PL_SOURCES="../samples/lissajous/logic/logic.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: lissajous[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../samples/lissajous/logic/logic.dll" -Fo"../samples/lissajous/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../samples/lissajous/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_lissajous

@del "..\samples\lissajous\logic\*.obj"  > nul 2> nul

:Cleanuprelease

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\samples\mask\logic\*.obj"  > nul 2> nul
@del "..\samples\screensaver\logic\*.obj"  > nul 2> nul
@del "..\samples\ptz\logic\*.obj"  > nul 2> nul
@del "..\samples\lissajous\logic\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../samples/lissajous/logic/lock.tmp" del "..\samples\lissajous\logic\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of release configuration
goto ExitLabel

:: ################################################################################
:: #                            configuration | debug                             #
:: ################################################################################

:debug

:: create output directories
@if not exist "../samples/mask/logic" @mkdir "../samples/mask/logic"

@if not exist "../samples/screensaver/logic" @mkdir "../samples/screensaver/logic"

@if not exist "../samples/ptz/logic" @mkdir "../samples/ptz/logic"

@if not exist "../samples/lissajous/logic" @mkdir "../samples/lissajous/logic"

:: create lock file(s)
@echo LOCKING > "../samples/lissajous/logic/lock.tmp"

@if exist "../samples/mask/logic/logic.dll" del "..\samples\mask\logic\logic.dll"
@if exist "../samples/mask/logic/logic_*.pdb" del "..\samples\mask\logic\logic_*.pdb"
@if exist "../samples/ptz/logic/logic.dll" del "..\samples\ptz\logic\logic.dll"
@if exist "../samples/ptz/logic/logic_*.pdb" del "..\samples\ptz\logic\logic_*.pdb"
@if exist "../samples/screensaver/logic/logic.dll" del "..\samples\screensaver\logic\logic.dll"
@if exist "../samples/screensaver/logic/logic_*.pdb" del "..\samples\screensaver\logic\logic_*.pdb"
@if exist "../samples/lissajous/logic/logic.dll" del "..\samples\lissajous\logic\logic.dll"
@if exist "../samples/lissajous/logic/logic_*.pdb" del "..\samples\lissajous\logic\logic_*.pdb"

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ mask | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../pilotlight/out/dcapp-genheader.exe ../samples/mask/mask.xml

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no 
@set PL_SOURCES="../samples/mask/logic/logic.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: mask[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../samples/mask/logic/logic.dll" -Fo"../samples/mask/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../samples/mask/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_mask

@del "..\samples\mask\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ptz | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../pilotlight/out/dcapp-genheader.exe ../samples/ptz/ptz.xml

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no 
@set PL_SOURCES="../samples/ptz/logic/logic.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: ptz[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../samples/ptz/logic/logic.dll" -Fo"../samples/ptz/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../samples/ptz/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_ptz

@del "..\samples\ptz\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ screensaver | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../pilotlight/out/dcapp-genheader.exe ../samples/screensaver/screensaver.xml

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no 
@set PL_SOURCES="../samples/screensaver/logic/logic.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: screensaver[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../samples/screensaver/logic/logic.dll" -Fo"../samples/screensaver/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../samples/screensaver/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_screensaver

@del "..\samples\screensaver\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ lissajous | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../pilotlight/out/dcapp-genheader.exe ../samples/lissajous/lissajous.xml

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no 
@set PL_SOURCES="../samples/lissajous/logic/logic.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: lissajous[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../samples/lissajous/logic/logic.dll" -Fo"../samples/lissajous/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../samples/lissajous/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_lissajous

@del "..\samples\lissajous\logic\*.obj"  > nul 2> nul

:Cleanupdebug

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\samples\mask\logic\*.obj"  > nul 2> nul
@del "..\samples\screensaver\logic\*.obj"  > nul 2> nul
@del "..\samples\ptz\logic\*.obj"  > nul 2> nul
@del "..\samples\lissajous\logic\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../samples/lissajous/logic/lock.tmp" del "..\samples\lissajous\logic\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of debug configuration
goto ExitLabel

:ExitLabel

:: return CWD to previous CWD
@popd
