
:: Project: apps
:: Auto Generated by:
:: "pl_build.py" version: 1.2.1

:: Project: apps

:: ################################################################################
:: #                              Development Setup                               #
:: ################################################################################

:: keep environment variables modifications local
@setlocal

:: make script directory CWD
@pushd %~dp0
@set dir=%~dp0

:: modify PATH to find vcvarsall.bat
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2019/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build;%PATH%

:: setup environment for MSVC dev tools
@call vcvarsall.bat amd64 > nul

:: default compilation result
@set PL_RESULT=[1m[92mSuccessful.[0m

:: default configuration
@set PL_CONFIG=release

:: check command line args for configuration
:CheckConfiguration
@if "%~1"=="-c" (@set PL_CONFIG=%2) & @shift & @shift & @goto CheckConfiguration
@if "%PL_CONFIG%" equ "release" ( goto release )
@if "%PL_CONFIG%" equ "debug" ( goto debug )

:: ################################################################################
:: #                           configuration | release                            #
:: ################################################################################

:release

:: create output directories
@if not exist "../pilotlight/out" @mkdir "../pilotlight/out"

:: create lock file(s)
@echo LOCKING > "../pilotlight/out/lock.tmp"

@if exist "../pilotlight/out/dcapp.dll" del "..\pilotlight\out\dcapp.dll"
@if exist "../pilotlight/out/dcapp_*.pdb" del "..\pilotlight\out\dcapp_*.pdb"
@if exist "../pilotlight/out/dcapp-genheader.exe" del "..\pilotlight\out\dcapp-genheader.exe"
@if exist "../pilotlight/out/dcapp-genheader_*.pdb" del "..\pilotlight\out\dcapp-genheader_*.pdb"

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ dcapp | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/dependencies/stb" -I"/include" -I"/include/libxml2" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nologo -noimplib -noexp 
@set PL_STATIC_LINK_LIBRARIES=libxml2.lib libcurl.lib 
@set PL_SOURCES="../src/value.c" "../src/trick.c" "../src/sock.c" "../src/pixelstream/mjpeg.c" "../src/utils/env.c" "../src/utils/math.c" "../src/utils/string.c" "../src/utils/file.c" "../src/app/elem.c" "../src/app/lookup.c" "../src/app/config.c" "../apps/dcapp.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dcapp[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dcapp.dll" -Fo"../pilotlight/out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dcapp_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dcapp

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~ dcapp-genheader | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~



@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/dependencies/stb" -I"/include" -I"/include/libxml2" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-incremental:no -nologo -noimplib -noexp 
@set PL_STATIC_LINK_LIBRARIES=libxml2.lib 
@set PL_SOURCES="../src/app/elem.c" "../src/app/lookup.c" "../src/app/config.c" "../src/utils/env.c" "../src/utils/math.c" "../src/utils/string.c" "../src/utils/file.c" "../src/value.c" "../apps/dcapp-genheader.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dcapp-genheader[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m

:: call compiler
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dcapp-genheader.exe" -Fo"../pilotlight/out/" -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dcapp-genheader_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dcapp-genheader

@del "..\pilotlight\out\*.obj"  > nul 2> nul

:Cleanuprelease

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\pilotlight\out\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../pilotlight/out/lock.tmp" del "..\pilotlight\out\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of release configuration
goto ExitLabel

:: ################################################################################
:: #                            configuration | debug                             #
:: ################################################################################

:debug

:: create output directories
@if not exist "../pilotlight/out" @mkdir "../pilotlight/out"

:: create lock file(s)
@echo LOCKING > "../pilotlight/out/lock.tmp"

@if exist "../pilotlight/out/dcapp.dll" del "..\pilotlight\out\dcapp.dll"
@if exist "../pilotlight/out/dcapp_*.pdb" del "..\pilotlight\out\dcapp_*.pdb"
@if exist "../pilotlight/out/dcapp-genheader.exe" del "..\pilotlight\out\dcapp-genheader.exe"
@if exist "../pilotlight/out/dcapp-genheader_*.pdb" del "..\pilotlight\out\dcapp-genheader_*.pdb"

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ dcapp | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/dependencies/stb" -I"/include" -I"/include/libxml2" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nologo -noimplib -noexp 
@set PL_STATIC_LINK_LIBRARIES=dearimguid.lib libxml2.lib libcurl.lib 
@set PL_SOURCES="../src/value.c" "../src/trick.c" "../src/sock.c" "../src/pixelstream/mjpeg.c" "../src/utils/env.c" "../src/utils/math.c" "../src/utils/string.c" "../src/utils/file.c" "../src/app/elem.c" "../src/app/lookup.c" "../src/app/config.c" "../apps/dcapp.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dcapp[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dcapp.dll" -Fo"../pilotlight/out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dcapp_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dcapp

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~ dcapp-genheader | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~



@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/dependencies/stb" -I"/include" -I"/include/libxml2" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-incremental:no -nologo -noimplib -noexp 
@set PL_STATIC_LINK_LIBRARIES=libxml2.lib 
@set PL_SOURCES="../src/app/elem.c" "../src/app/lookup.c" "../src/app/config.c" "../src/utils/env.c" "../src/utils/math.c" "../src/utils/string.c" "../src/utils/file.c" "../src/value.c" "../apps/dcapp-genheader.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dcapp-genheader[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m

:: call compiler
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dcapp-genheader.exe" -Fo"../pilotlight/out/" -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dcapp-genheader_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dcapp-genheader

@del "..\pilotlight\out\*.obj"  > nul 2> nul

:Cleanupdebug

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\pilotlight\out\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../pilotlight/out/lock.tmp" del "..\pilotlight\out\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of debug configuration
goto ExitLabel

:ExitLabel

:: return CWD to previous CWD
@popd
