
:: Project: apps
:: Auto Generated by:
:: "pl_build.py" version: 1.3.0

:: Project: apps

:: ################################################################################
:: #                              Development Setup                               #
:: ################################################################################

:: keep environment variables modifications local
@setlocal

:: make script directory CWD
@pushd %~dp0
@set dir=%~dp0

:: modify PATH to find vcvarsall.bat
@if exist "C:/Program Files/Microsoft Visual Studio/18/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/18/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\18\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/18/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/18/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\18\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/18/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%

:: setup environment for MSVC dev tools
@call vcvarsall.bat amd64 > nul

:: default compilation result
@set PL_RESULT=[1m[92mSuccessful.[0m

:: default configuration
@set PL_CONFIG=release

:: check command line args for configuration
:CheckConfiguration
@if "%~1"=="-c" (@set PL_CONFIG=%2) & @shift & @shift & @goto CheckConfiguration
@if "%PL_CONFIG%" equ "release" ( goto release )
@if "%PL_CONFIG%" equ "debug" ( goto debug )

:: ################################################################################
:: #                           configuration | release                            #
:: ################################################################################

:release

:: create output directories
@if not exist "../pilotlight/out" @mkdir "../pilotlight/out"

:: create lock file(s)
@echo LOCKING > "../pilotlight/out/lock.tmp"

@if exist "../pilotlight/out/dc_draw_ext.dll" del "..\pilotlight\out\dc_draw_ext.dll"
@if exist "../pilotlight/out/dc_draw_ext_*.pdb" del "..\pilotlight\out\dc_draw_ext_*.pdb"
@if exist "../pilotlight/out/dc_draw_backend_ext.dll" del "..\pilotlight\out\dc_draw_backend_ext.dll"
@if exist "../pilotlight/out/dc_draw_backend_ext_*.pdb" del "..\pilotlight\out\dc_draw_backend_ext_*.pdb"
@if exist "../pilotlight/out/pl_planet_processor_ext.dll" del "..\pilotlight\out\pl_planet_processor_ext.dll"
@if exist "../pilotlight/out/pl_planet_processor_ext_*.pdb" del "..\pilotlight\out\pl_planet_processor_ext_*.pdb"
@if exist "../pilotlight/out/pl_planet_ext.dll" del "..\pilotlight\out\pl_planet_ext.dll"
@if exist "../pilotlight/out/pl_planet_ext_*.pdb" del "..\pilotlight\out\pl_planet_ext_*.pdb"
@if exist "../pilotlight/out/dcapp.dll" del "..\pilotlight\out\dcapp.dll"
@if exist "../pilotlight/out/dcapp_*.pdb" del "..\pilotlight\out\dcapp_*.pdb"
@if exist "../pilotlight/out/dcapp-genheader.exe" del "..\pilotlight\out\dcapp-genheader.exe"
@if exist "../pilotlight/out/dcapp-genheader_*.pdb" del "..\pilotlight\out\dcapp-genheader_*.pdb"
@if exist "../pilotlight/out/dcapp-validate.exe" del "..\pilotlight\out\dcapp-validate.exe"
@if exist "../pilotlight/out/dcapp-validate_*.pdb" del "..\pilotlight\out\dcapp-validate_*.pdb"
@if exist "../pilotlight/out/dcapp-planet-chunkgen.dll" del "..\pilotlight\out\dcapp-planet-chunkgen.dll"
@if exist "../pilotlight/out/dcapp-planet-chunkgen_*.pdb" del "..\pilotlight\out\dcapp-planet-chunkgen_*.pdb"

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~ dc_draw_ext | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nologo -noimplib -noexp 
@set PL_SOURCES="../extensions/dc_draw_ext.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dc_draw_ext[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dc_draw_ext.dll" -Fo"../pilotlight/out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dc_draw_ext_%random%.pdb" %PL_LINK_DIRECTORIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dc_draw_ext

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~ dc_draw_backend_ext | release ~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nologo -noimplib -noexp 
@set PL_SOURCES="../extensions/dc_draw_backend_ext.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dc_draw_backend_ext[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dc_draw_backend_ext.dll" -Fo"../pilotlight/out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dc_draw_backend_ext_%random%.pdb" %PL_LINK_DIRECTORIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dc_draw_backend_ext

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~ pl_planet_processor_ext | release ~~~~~~~~~~~~~~~~~~~~~~~

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nologo -noimplib -noexp 
@set PL_SOURCES="../extensions/pl_planet_processor_ext.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pl_planet_processor_ext[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/pl_planet_processor_ext.dll" -Fo"../pilotlight/out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/pl_planet_processor_ext_%random%.pdb" %PL_LINK_DIRECTORIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_pl_planet_processor_ext

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~ pl_planet_ext | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nologo -noimplib -noexp 
@set PL_SOURCES="../extensions/pl_planet_ext.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pl_planet_ext[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/pl_planet_ext.dll" -Fo"../pilotlight/out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/pl_planet_ext_%random%.pdb" %PL_LINK_DIRECTORIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_pl_planet_ext

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ dcapp | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

xcopy /Y /I "../vcpkg_installed/x64-windows\bin\*.dll" "../pilotlight/out\"

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" -I"../vcpkg_installed/x64-windows/include/libxml2" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nologo -noimplib -noexp 
@set PL_STATIC_LINK_LIBRARIES=libxml2.lib libcurl.lib 
@set PL_SOURCES="../src/app/config.c" "../src/app/elem.c" "../src/app/lookup.c" "../src/edge.c" "../src/pixelstream/mjpeg.c" "../src/pixelstream/shmem.c" "../src/sock.c" "../src/trick.c" "../src/utils/env.c" "../src/utils/file.c" "../src/utils/log.c" "../src/utils/math.c" "../src/utils/string.c" "../src/utils/time.c" "../src/value.c" "../apps/dcapp.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dcapp[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dcapp.dll" -Fo"../pilotlight/out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dcapp_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dcapp

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~ dcapp-genheader | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~

xcopy /Y /I "../vcpkg_installed/x64-windows\bin\*.dll" "../pilotlight/out\"

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" -I"../vcpkg_installed/x64-windows/include/libxml2" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-incremental:no -nologo -noimplib -noexp 
@set PL_STATIC_LINK_LIBRARIES=libxml2.lib 
@set PL_SOURCES="../src/app/config.c" "../src/app/elem.c" "../src/app/lookup.c" "../src/utils/env.c" "../src/utils/file.c" "../src/utils/log.c" "../src/utils/math.c" "../src/utils/string.c" "../src/utils/time.c" "../src/value.c" "../apps/dcapp-genheader.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dcapp-genheader[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m

:: call compiler
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dcapp-genheader.exe" -Fo"../pilotlight/out/" -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dcapp-genheader_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dcapp-genheader

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~ dcapp-validate | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~

xcopy /Y /I "../vcpkg_installed/x64-windows\bin\*.dll" "../pilotlight/out\"

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" -I"../vcpkg_installed/x64-windows/include/libxml2" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-incremental:no -nologo -noimplib -noexp 
@set PL_STATIC_LINK_LIBRARIES=libxml2.lib 
@set PL_SOURCES="../src/app/config.c" "../src/app/elem.c" "../src/app/lookup.c" "../src/utils/env.c" "../src/utils/file.c" "../src/utils/log.c" "../src/utils/math.c" "../src/utils/string.c" "../src/utils/time.c" "../src/value.c" "../apps/dcapp-validate.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dcapp-validate[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m

:: call compiler
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dcapp-validate.exe" -Fo"../pilotlight/out/" -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dcapp-validate_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dcapp-validate

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~ dcapp-planet-chunkgen | release ~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nologo -noimplib -noexp 
@set PL_SOURCES="../apps/dcapp-planet-chunkgen.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dcapp-planet-chunkgen[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dcapp-planet-chunkgen.dll" -Fo"../pilotlight/out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dcapp-planet-chunkgen_%random%.pdb" %PL_LINK_DIRECTORIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dcapp-planet-chunkgen

@del "..\pilotlight\out\*.obj"  > nul 2> nul

:Cleanuprelease

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\pilotlight\out\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../pilotlight/out/lock.tmp" del "..\pilotlight\out\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of release configuration
goto ExitLabel

:: ################################################################################
:: #                            configuration | debug                             #
:: ################################################################################

:debug

:: create output directories
@if not exist "../pilotlight/out" @mkdir "../pilotlight/out"

:: create lock file(s)
@echo LOCKING > "../pilotlight/out/lock.tmp"

@if exist "../pilotlight/out/dc_draw_ext.dll" del "..\pilotlight\out\dc_draw_ext.dll"
@if exist "../pilotlight/out/dc_draw_ext_*.pdb" del "..\pilotlight\out\dc_draw_ext_*.pdb"
@if exist "../pilotlight/out/dc_draw_backend_ext.dll" del "..\pilotlight\out\dc_draw_backend_ext.dll"
@if exist "../pilotlight/out/dc_draw_backend_ext_*.pdb" del "..\pilotlight\out\dc_draw_backend_ext_*.pdb"
@if exist "../pilotlight/out/pl_planet_processor_ext.dll" del "..\pilotlight\out\pl_planet_processor_ext.dll"
@if exist "../pilotlight/out/pl_planet_processor_ext_*.pdb" del "..\pilotlight\out\pl_planet_processor_ext_*.pdb"
@if exist "../pilotlight/out/pl_planet_ext.dll" del "..\pilotlight\out\pl_planet_ext.dll"
@if exist "../pilotlight/out/pl_planet_ext_*.pdb" del "..\pilotlight\out\pl_planet_ext_*.pdb"
@if exist "../pilotlight/out/dcapp.dll" del "..\pilotlight\out\dcapp.dll"
@if exist "../pilotlight/out/dcapp_*.pdb" del "..\pilotlight\out\dcapp_*.pdb"
@if exist "../pilotlight/out/dcapp-genheader.exe" del "..\pilotlight\out\dcapp-genheader.exe"
@if exist "../pilotlight/out/dcapp-genheader_*.pdb" del "..\pilotlight\out\dcapp-genheader_*.pdb"
@if exist "../pilotlight/out/dcapp-validate.exe" del "..\pilotlight\out\dcapp-validate.exe"
@if exist "../pilotlight/out/dcapp-validate_*.pdb" del "..\pilotlight\out\dcapp-validate_*.pdb"
@if exist "../pilotlight/out/dcapp-planet-chunkgen.dll" del "..\pilotlight\out\dcapp-planet-chunkgen.dll"
@if exist "../pilotlight/out/dcapp-planet-chunkgen_*.pdb" del "..\pilotlight\out\dcapp-planet-chunkgen_*.pdb"

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ dc_draw_ext | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nologo -noimplib -noexp 
@set PL_SOURCES="../extensions/dc_draw_ext.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dc_draw_ext[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dc_draw_ext.dll" -Fo"../pilotlight/out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dc_draw_ext_%random%.pdb" %PL_LINK_DIRECTORIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dc_draw_ext

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~ dc_draw_backend_ext | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nologo -noimplib -noexp 
@set PL_SOURCES="../extensions/dc_draw_backend_ext.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dc_draw_backend_ext[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dc_draw_backend_ext.dll" -Fo"../pilotlight/out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dc_draw_backend_ext_%random%.pdb" %PL_LINK_DIRECTORIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dc_draw_backend_ext

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~ pl_planet_processor_ext | debug ~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nologo -noimplib -noexp 
@set PL_SOURCES="../extensions/pl_planet_processor_ext.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pl_planet_processor_ext[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/pl_planet_processor_ext.dll" -Fo"../pilotlight/out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/pl_planet_processor_ext_%random%.pdb" %PL_LINK_DIRECTORIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_pl_planet_processor_ext

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~ pl_planet_ext | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nologo -noimplib -noexp 
@set PL_SOURCES="../extensions/pl_planet_ext.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pl_planet_ext[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/pl_planet_ext.dll" -Fo"../pilotlight/out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/pl_planet_ext_%random%.pdb" %PL_LINK_DIRECTORIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_pl_planet_ext

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ dcapp | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

xcopy /Y /I "../vcpkg_installed/x64-windows\bin\*.dll" "../pilotlight/out\"

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" -I"../vcpkg_installed/x64-windows/include/libxml2" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nologo -noimplib -noexp 
@set PL_STATIC_LINK_LIBRARIES=dearimguid.lib libxml2.lib libcurl.lib 
@set PL_SOURCES="../src/app/config.c" "../src/app/elem.c" "../src/app/lookup.c" "../src/edge.c" "../src/pixelstream/mjpeg.c" "../src/pixelstream/shmem.c" "../src/sock.c" "../src/trick.c" "../src/utils/env.c" "../src/utils/file.c" "../src/utils/log.c" "../src/utils/math.c" "../src/utils/string.c" "../src/utils/time.c" "../src/value.c" "../apps/dcapp.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dcapp[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dcapp.dll" -Fo"../pilotlight/out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dcapp_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dcapp

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~ dcapp-genheader | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

xcopy /Y /I "../vcpkg_installed/x64-windows\bin\*.dll" "../pilotlight/out\"

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" -I"../vcpkg_installed/x64-windows/include/libxml2" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-incremental:no -nologo -noimplib -noexp 
@set PL_STATIC_LINK_LIBRARIES=libxml2.lib 
@set PL_SOURCES="../src/app/config.c" "../src/app/elem.c" "../src/app/lookup.c" "../src/utils/env.c" "../src/utils/file.c" "../src/utils/log.c" "../src/utils/math.c" "../src/utils/string.c" "../src/utils/time.c" "../src/value.c" "../apps/dcapp-genheader.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dcapp-genheader[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m

:: call compiler
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dcapp-genheader.exe" -Fo"../pilotlight/out/" -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dcapp-genheader_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dcapp-genheader

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~ dcapp-validate | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

xcopy /Y /I "../vcpkg_installed/x64-windows\bin\*.dll" "../pilotlight/out\"

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" -I"../vcpkg_installed/x64-windows/include/libxml2" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-incremental:no -nologo -noimplib -noexp 
@set PL_STATIC_LINK_LIBRARIES=libxml2.lib 
@set PL_SOURCES="../src/app/config.c" "../src/app/elem.c" "../src/app/lookup.c" "../src/utils/env.c" "../src/utils/file.c" "../src/utils/log.c" "../src/utils/math.c" "../src/utils/string.c" "../src/utils/time.c" "../src/value.c" "../apps/dcapp-validate.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dcapp-validate[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m

:: call compiler
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dcapp-validate.exe" -Fo"../pilotlight/out/" -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dcapp-validate_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dcapp-validate

@del "..\pilotlight\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~ dcapp-planet-chunkgen | debug ~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_INCLUDE_DIRECTORIES=-I"../src" -I"../extensions" -I"../shaders" -I"../pilotlight/src" -I"../pilotlight/libs" -I"../pilotlight/extensions" -I"../pilotlight/shaders" -I"../pilotlight/dependencies/stb" -I"../vcpkg_installed/x64-windows/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../pilotlight/out" -LIBPATH:"../vcpkg_installed/x64-windows/lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nologo -noimplib -noexp 
@set PL_SOURCES="../apps/dcapp-planet-chunkgen.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: dcapp-planet-chunkgen[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../pilotlight/out/dcapp-planet-chunkgen.dll" -Fo"../pilotlight/out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../pilotlight/out/dcapp-planet-chunkgen_%random%.pdb" %PL_LINK_DIRECTORIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_dcapp-planet-chunkgen

@del "..\pilotlight\out\*.obj"  > nul 2> nul

:Cleanupdebug

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\pilotlight\out\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../pilotlight/out/lock.tmp" del "..\pilotlight\out\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of debug configuration
goto ExitLabel

:ExitLabel

:: return CWD to previous CWD
@popd
