
:: Project: samples
:: Auto Generated by:
:: "pl_build.py" version: 1.5.0

:: Project: samples

:: ################################################################################
:: #                              Development Setup                               #
:: ################################################################################

:: keep environment variables modifications local
@setlocal

:: make script directory CWD
@pushd %~dp0
@set dir=%~dp0

:: modify PATH to find vcvarsall.bat
@if exist "C:/Program Files/Microsoft Visual Studio/18/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/18/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\18\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/18/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/18/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\18\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/18/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%

:: setup environment for MSVC dev tools
@call vcvarsall.bat amd64 > nul

:: default compilation result
@set PL_RESULT=[1m[92mSuccessful.[0m

:: default configuration
@set PL_CONFIG=release

:: check command line args for configuration
:CheckConfiguration
@if "%~1"=="-c" (@set PL_CONFIG=%2) & @shift & @shift & @goto CheckConfiguration
@if "%PL_CONFIG%" equ "release" ( goto release )
@if "%PL_CONFIG%" equ "debug" ( goto debug )

:: ################################################################################
:: #                           configuration | release                            #
:: ################################################################################

:release

:: create output directories
@if not exist "../../samples/planet/logic" @mkdir "../../samples/planet/logic"

@if not exist "../../samples/lissajous/logic" @mkdir "../../samples/lissajous/logic"

@if not exist "../../samples/api-test/logic" @mkdir "../../samples/api-test/logic"

@if not exist "../../samples/starfield/logic" @mkdir "../../samples/starfield/logic"

@if not exist "../../samples/procedural-panel/logic" @mkdir "../../samples/procedural-panel/logic"

:: create lock file(s)
@echo LOCKING > "../../samples/starfield/logic/lock.tmp"

@if exist "../../samples/api-test/logic/logic.dll" del "..\..\samples\api-test\logic\logic.dll"
@if exist "../../samples/api-test/logic/logic_*.pdb" del "..\..\samples\api-test\logic\logic_*.pdb"
@if exist "../../samples/lissajous/logic/logic.dll" del "..\..\samples\lissajous\logic\logic.dll"
@if exist "../../samples/lissajous/logic/logic_*.pdb" del "..\..\samples\lissajous\logic\logic_*.pdb"
@if exist "../../samples/planet/logic/logic.dll" del "..\..\samples\planet\logic\logic.dll"
@if exist "../../samples/planet/logic/logic_*.pdb" del "..\..\samples\planet\logic\logic_*.pdb"
@if exist "../../samples/procedural-panel/logic/logic.dll" del "..\..\samples\procedural-panel\logic\logic.dll"
@if exist "../../samples/procedural-panel/logic/logic_*.pdb" del "..\..\samples\procedural-panel\logic\logic_*.pdb"
@if exist "../../samples/starfield/logic/logic.dll" del "..\..\samples\starfield\logic\logic.dll"
@if exist "../../samples/starfield/logic/logic_*.pdb" del "..\..\samples\starfield\logic\logic_*.pdb"

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ api-test | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/api-test/api-test.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -std:c11 -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -DNDEBUG
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/api-test/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: api-test[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/api-test/logic/logic.dll" -Fo"../../samples/api-test/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/api-test/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_api-test

@del "..\..\samples\api-test\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ lissajous | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/lissajous/lissajous.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -std:c11 -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -DNDEBUG
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/lissajous/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: lissajous[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/lissajous/logic/logic.dll" -Fo"../../samples/lissajous/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/lissajous/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_lissajous

@del "..\..\samples\lissajous\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ planet | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/planet/planet.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -std:c11 -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -DNDEBUG
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/planet/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: planet[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/planet/logic/logic.dll" -Fo"../../samples/planet/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/planet/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_planet

@del "..\..\samples\planet\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~ procedural-panel | release ~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/procedural-panel/procedural-panel.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -std:c11 -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -DNDEBUG
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/procedural-panel/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: procedural-panel[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/procedural-panel/logic/logic.dll" -Fo"../../samples/procedural-panel/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/procedural-panel/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_procedural-panel

@del "..\..\samples\procedural-panel\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ starfield | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/starfield/starfield.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -std:c11 -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -DNDEBUG
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/starfield/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: starfield[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/starfield/logic/logic.dll" -Fo"../../samples/starfield/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/starfield/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_starfield

@del "..\..\samples\starfield\logic\*.obj"  > nul 2> nul

:Cleanuprelease

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\..\samples\planet\logic\*.obj"  > nul 2> nul
@del "..\..\samples\lissajous\logic\*.obj"  > nul 2> nul
@del "..\..\samples\api-test\logic\*.obj"  > nul 2> nul
@del "..\..\samples\starfield\logic\*.obj"  > nul 2> nul
@del "..\..\samples\procedural-panel\logic\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../../samples/starfield/logic/lock.tmp" del "..\..\samples\starfield\logic\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of release configuration
goto ExitLabel

:: ################################################################################
:: #                            configuration | debug                             #
:: ################################################################################

:debug

:: create output directories
@if not exist "../../samples/planet/logic" @mkdir "../../samples/planet/logic"

@if not exist "../../samples/lissajous/logic" @mkdir "../../samples/lissajous/logic"

@if not exist "../../samples/api-test/logic" @mkdir "../../samples/api-test/logic"

@if not exist "../../samples/starfield/logic" @mkdir "../../samples/starfield/logic"

@if not exist "../../samples/procedural-panel/logic" @mkdir "../../samples/procedural-panel/logic"

:: create lock file(s)
@echo LOCKING > "../../samples/starfield/logic/lock.tmp"

@if exist "../../samples/api-test/logic/logic.dll" del "..\..\samples\api-test\logic\logic.dll"
@if exist "../../samples/api-test/logic/logic_*.pdb" del "..\..\samples\api-test\logic\logic_*.pdb"
@if exist "../../samples/lissajous/logic/logic.dll" del "..\..\samples\lissajous\logic\logic.dll"
@if exist "../../samples/lissajous/logic/logic_*.pdb" del "..\..\samples\lissajous\logic\logic_*.pdb"
@if exist "../../samples/planet/logic/logic.dll" del "..\..\samples\planet\logic\logic.dll"
@if exist "../../samples/planet/logic/logic_*.pdb" del "..\..\samples\planet\logic\logic_*.pdb"
@if exist "../../samples/procedural-panel/logic/logic.dll" del "..\..\samples\procedural-panel\logic\logic.dll"
@if exist "../../samples/procedural-panel/logic/logic_*.pdb" del "..\..\samples\procedural-panel\logic\logic_*.pdb"
@if exist "../../samples/starfield/logic/logic.dll" del "..\..\samples\starfield\logic\logic.dll"
@if exist "../../samples/starfield/logic/logic_*.pdb" del "..\..\samples\starfield\logic\logic_*.pdb"

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ api-test | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/api-test/api-test.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -std:c11 -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/api-test/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: api-test[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/api-test/logic/logic.dll" -Fo"../../samples/api-test/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/api-test/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_api-test

@del "..\..\samples\api-test\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ lissajous | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/lissajous/lissajous.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -std:c11 -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/lissajous/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: lissajous[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/lissajous/logic/logic.dll" -Fo"../../samples/lissajous/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/lissajous/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_lissajous

@del "..\..\samples\lissajous\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ planet | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/planet/planet.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -std:c11 -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/planet/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: planet[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/planet/logic/logic.dll" -Fo"../../samples/planet/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/planet/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_planet

@del "..\..\samples\planet\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~ procedural-panel | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/procedural-panel/procedural-panel.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -std:c11 -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/procedural-panel/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: procedural-panel[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/procedural-panel/logic/logic.dll" -Fo"../../samples/procedural-panel/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/procedural-panel/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_procedural-panel

@del "..\..\samples\procedural-panel\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ starfield | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/starfield/starfield.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -std:c11 -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/starfield/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: starfield[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/starfield/logic/logic.dll" -Fo"../../samples/starfield/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/starfield/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_starfield

@del "..\..\samples\starfield\logic\*.obj"  > nul 2> nul

:Cleanupdebug

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\..\samples\planet\logic\*.obj"  > nul 2> nul
@del "..\..\samples\lissajous\logic\*.obj"  > nul 2> nul
@del "..\..\samples\api-test\logic\*.obj"  > nul 2> nul
@del "..\..\samples\starfield\logic\*.obj"  > nul 2> nul
@del "..\..\samples\procedural-panel\logic\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../../samples/starfield/logic/lock.tmp" del "..\..\samples\starfield\logic\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of debug configuration
goto ExitLabel

:ExitLabel

:: return CWD to previous CWD
@popd
exit /b %PL_BUILD_STATUS%
