
:: Project: samples
:: Auto Generated by:
:: "pl_build.py" version: 1.5.0

:: Project: samples

:: ################################################################################
:: #                              Development Setup                               #
:: ################################################################################

:: keep environment variables modifications local
@setlocal

:: make script directory CWD
@pushd %~dp0
@set dir=%~dp0

:: modify PATH to find vcvarsall.bat
@if exist "C:/Program Files/Microsoft Visual Studio/18/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/18/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\18\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/18/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/18/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\18\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/18/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%

:: setup environment for MSVC dev tools
@call vcvarsall.bat amd64 > nul

:: default compilation result
@set PL_RESULT=[1m[92mSuccessful.[0m

:: default configuration
@set PL_CONFIG=release

:: check command line args for configuration
:CheckConfiguration
@if "%~1"=="-c" (@set PL_CONFIG=%2) & @shift & @shift & @goto CheckConfiguration
@if "%PL_CONFIG%" equ "release" ( goto release )
@if "%PL_CONFIG%" equ "debug" ( goto debug )

:: ################################################################################
:: #                           configuration | release                            #
:: ################################################################################

:release

:: create output directories
@if not exist "../../samples/drawfunction3/logic" @mkdir "../../samples/drawfunction3/logic"

@if not exist "../../samples/mask/logic" @mkdir "../../samples/mask/logic"

@if not exist "../../samples/ptz/logic" @mkdir "../../samples/ptz/logic"

@if not exist "../../samples/screensaver/logic" @mkdir "../../samples/screensaver/logic"

@if not exist "../../samples/functions/logic" @mkdir "../../samples/functions/logic"

@if not exist "../../samples/lissajous/logic" @mkdir "../../samples/lissajous/logic"

@if not exist "../../samples/planet/logic" @mkdir "../../samples/planet/logic"

@if not exist "../../samples/drawfunction2/logic" @mkdir "../../samples/drawfunction2/logic"

@if not exist "../../samples/drawfunction1/logic" @mkdir "../../samples/drawfunction1/logic"

:: create lock file(s)
@echo LOCKING > "../../samples/screensaver/logic/lock.tmp"

@if exist "../../samples/drawfunction1/logic/logic.dll" del "..\..\samples\drawfunction1\logic\logic.dll"
@if exist "../../samples/drawfunction1/logic/logic_*.pdb" del "..\..\samples\drawfunction1\logic\logic_*.pdb"
@if exist "../../samples/drawfunction2/logic/logic.dll" del "..\..\samples\drawfunction2\logic\logic.dll"
@if exist "../../samples/drawfunction2/logic/logic_*.pdb" del "..\..\samples\drawfunction2\logic\logic_*.pdb"
@if exist "../../samples/drawfunction3/logic/logic.dll" del "..\..\samples\drawfunction3\logic\logic.dll"
@if exist "../../samples/drawfunction3/logic/logic_*.pdb" del "..\..\samples\drawfunction3\logic\logic_*.pdb"
@if exist "../../samples/functions/logic/logic.dll" del "..\..\samples\functions\logic\logic.dll"
@if exist "../../samples/functions/logic/logic_*.pdb" del "..\..\samples\functions\logic\logic_*.pdb"
@if exist "../../samples/lissajous/logic/logic.dll" del "..\..\samples\lissajous\logic\logic.dll"
@if exist "../../samples/lissajous/logic/logic_*.pdb" del "..\..\samples\lissajous\logic\logic_*.pdb"
@if exist "../../samples/mask/logic/logic.dll" del "..\..\samples\mask\logic\logic.dll"
@if exist "../../samples/mask/logic/logic_*.pdb" del "..\..\samples\mask\logic\logic_*.pdb"
@if exist "../../samples/planet/logic/logic.dll" del "..\..\samples\planet\logic\logic.dll"
@if exist "../../samples/planet/logic/logic_*.pdb" del "..\..\samples\planet\logic\logic_*.pdb"
@if exist "../../samples/ptz/logic/logic.dll" del "..\..\samples\ptz\logic\logic.dll"
@if exist "../../samples/ptz/logic/logic_*.pdb" del "..\..\samples\ptz\logic\logic_*.pdb"
@if exist "../../samples/screensaver/logic/logic.dll" del "..\..\samples\screensaver\logic\logic.dll"
@if exist "../../samples/screensaver/logic/logic_*.pdb" del "..\..\samples\screensaver\logic\logic_*.pdb"

::~~~~~~~~~~~~~~~~~~~~~~~~~~~ drawfunction1 | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/drawfunction1/drawfunction1.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -DNDEBUG
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/drawfunction1/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: drawfunction1[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/drawfunction1/logic/logic.dll" -Fo"../../samples/drawfunction1/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/drawfunction1/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_drawfunction1

@del "..\..\samples\drawfunction1\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~ drawfunction2 | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/drawfunction2/drawfunction2.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -DNDEBUG
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/drawfunction2/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: drawfunction2[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/drawfunction2/logic/logic.dll" -Fo"../../samples/drawfunction2/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/drawfunction2/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_drawfunction2

@del "..\..\samples\drawfunction2\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~ drawfunction3 | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/drawfunction3/drawfunction3.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -DNDEBUG
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/drawfunction3/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: drawfunction3[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/drawfunction3/logic/logic.dll" -Fo"../../samples/drawfunction3/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/drawfunction3/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_drawfunction3

@del "..\..\samples\drawfunction3\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ functions | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/functions/functions.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -DNDEBUG
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/functions/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: functions[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/functions/logic/logic.dll" -Fo"../../samples/functions/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/functions/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_functions

@del "..\..\samples\functions\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ lissajous | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/lissajous/lissajous.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -DNDEBUG
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/lissajous/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: lissajous[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/lissajous/logic/logic.dll" -Fo"../../samples/lissajous/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/lissajous/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_lissajous

@del "..\..\samples\lissajous\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ mask | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/mask/mask.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -DNDEBUG
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/mask/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: mask[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/mask/logic/logic.dll" -Fo"../../samples/mask/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/mask/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_mask

@del "..\..\samples\mask\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ planet | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/planet/planet.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -DNDEBUG
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/planet/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: planet[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/planet/logic/logic.dll" -Fo"../../samples/planet/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/planet/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_planet

@del "..\..\samples\planet\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ptz | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/ptz/ptz.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -DNDEBUG
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/ptz/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: ptz[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/ptz/logic/logic.dll" -Fo"../../samples/ptz/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/ptz/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_ptz

@del "..\..\samples\ptz\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~ screensaver | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/screensaver/screensaver.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -DNDEBUG
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/screensaver/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: screensaver[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/screensaver/logic/logic.dll" -Fo"../../samples/screensaver/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/screensaver/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_screensaver

@del "..\..\samples\screensaver\logic\*.obj"  > nul 2> nul

:Cleanuprelease

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\..\samples\drawfunction3\logic\*.obj"  > nul 2> nul
@del "..\..\samples\mask\logic\*.obj"  > nul 2> nul
@del "..\..\samples\ptz\logic\*.obj"  > nul 2> nul
@del "..\..\samples\screensaver\logic\*.obj"  > nul 2> nul
@del "..\..\samples\functions\logic\*.obj"  > nul 2> nul
@del "..\..\samples\lissajous\logic\*.obj"  > nul 2> nul
@del "..\..\samples\planet\logic\*.obj"  > nul 2> nul
@del "..\..\samples\drawfunction2\logic\*.obj"  > nul 2> nul
@del "..\..\samples\drawfunction1\logic\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../../samples/screensaver/logic/lock.tmp" del "..\..\samples\screensaver\logic\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of release configuration
goto ExitLabel

:: ################################################################################
:: #                            configuration | debug                             #
:: ################################################################################

:debug

:: create output directories
@if not exist "../../samples/drawfunction3/logic" @mkdir "../../samples/drawfunction3/logic"

@if not exist "../../samples/mask/logic" @mkdir "../../samples/mask/logic"

@if not exist "../../samples/ptz/logic" @mkdir "../../samples/ptz/logic"

@if not exist "../../samples/screensaver/logic" @mkdir "../../samples/screensaver/logic"

@if not exist "../../samples/functions/logic" @mkdir "../../samples/functions/logic"

@if not exist "../../samples/lissajous/logic" @mkdir "../../samples/lissajous/logic"

@if not exist "../../samples/planet/logic" @mkdir "../../samples/planet/logic"

@if not exist "../../samples/drawfunction2/logic" @mkdir "../../samples/drawfunction2/logic"

@if not exist "../../samples/drawfunction1/logic" @mkdir "../../samples/drawfunction1/logic"

:: create lock file(s)
@echo LOCKING > "../../samples/screensaver/logic/lock.tmp"

@if exist "../../samples/drawfunction1/logic/logic.dll" del "..\..\samples\drawfunction1\logic\logic.dll"
@if exist "../../samples/drawfunction1/logic/logic_*.pdb" del "..\..\samples\drawfunction1\logic\logic_*.pdb"
@if exist "../../samples/drawfunction2/logic/logic.dll" del "..\..\samples\drawfunction2\logic\logic.dll"
@if exist "../../samples/drawfunction2/logic/logic_*.pdb" del "..\..\samples\drawfunction2\logic\logic_*.pdb"
@if exist "../../samples/drawfunction3/logic/logic.dll" del "..\..\samples\drawfunction3\logic\logic.dll"
@if exist "../../samples/drawfunction3/logic/logic_*.pdb" del "..\..\samples\drawfunction3\logic\logic_*.pdb"
@if exist "../../samples/functions/logic/logic.dll" del "..\..\samples\functions\logic\logic.dll"
@if exist "../../samples/functions/logic/logic_*.pdb" del "..\..\samples\functions\logic\logic_*.pdb"
@if exist "../../samples/lissajous/logic/logic.dll" del "..\..\samples\lissajous\logic\logic.dll"
@if exist "../../samples/lissajous/logic/logic_*.pdb" del "..\..\samples\lissajous\logic\logic_*.pdb"
@if exist "../../samples/mask/logic/logic.dll" del "..\..\samples\mask\logic\logic.dll"
@if exist "../../samples/mask/logic/logic_*.pdb" del "..\..\samples\mask\logic\logic_*.pdb"
@if exist "../../samples/planet/logic/logic.dll" del "..\..\samples\planet\logic\logic.dll"
@if exist "../../samples/planet/logic/logic_*.pdb" del "..\..\samples\planet\logic\logic_*.pdb"
@if exist "../../samples/ptz/logic/logic.dll" del "..\..\samples\ptz\logic\logic.dll"
@if exist "../../samples/ptz/logic/logic_*.pdb" del "..\..\samples\ptz\logic\logic_*.pdb"
@if exist "../../samples/screensaver/logic/logic.dll" del "..\..\samples\screensaver\logic\logic.dll"
@if exist "../../samples/screensaver/logic/logic_*.pdb" del "..\..\samples\screensaver\logic\logic_*.pdb"

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~ drawfunction1 | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/drawfunction1/drawfunction1.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/drawfunction1/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: drawfunction1[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/drawfunction1/logic/logic.dll" -Fo"../../samples/drawfunction1/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/drawfunction1/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_drawfunction1

@del "..\..\samples\drawfunction1\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~ drawfunction2 | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/drawfunction2/drawfunction2.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/drawfunction2/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: drawfunction2[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/drawfunction2/logic/logic.dll" -Fo"../../samples/drawfunction2/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/drawfunction2/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_drawfunction2

@del "..\..\samples\drawfunction2\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~ drawfunction3 | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/drawfunction3/drawfunction3.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/drawfunction3/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: drawfunction3[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/drawfunction3/logic/logic.dll" -Fo"../../samples/drawfunction3/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/drawfunction3/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_drawfunction3

@del "..\..\samples\drawfunction3\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ functions | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/functions/functions.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/functions/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: functions[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/functions/logic/logic.dll" -Fo"../../samples/functions/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/functions/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_functions

@del "..\..\samples\functions\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ lissajous | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/lissajous/lissajous.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/lissajous/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: lissajous[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/lissajous/logic/logic.dll" -Fo"../../samples/lissajous/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/lissajous/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_lissajous

@del "..\..\samples\lissajous\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ mask | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/mask/mask.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/mask/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: mask[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/mask/logic/logic.dll" -Fo"../../samples/mask/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/mask/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_mask

@del "..\..\samples\mask\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ planet | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/planet/planet.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/planet/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: planet[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/planet/logic/logic.dll" -Fo"../../samples/planet/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/planet/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_planet

@del "..\..\samples\planet\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ptz | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/ptz/ptz.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/ptz/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: ptz[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/ptz/logic/logic.dll" -Fo"../../samples/ptz/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/ptz/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_ptz

@del "..\..\samples\ptz\logic\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ screensaver | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"../../pilotlight/out/dcapp-genheader.exe" ../../samples/screensaver/screensaver.xml || exit /b 1

@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi
@set PL_LINKER_FLAGS=-noexp -nologo -noimplib -incremental:no -EXPORT:display_pre_init -EXPORT:display_init -EXPORT:display_draw -EXPORT:display_close
@set PL_SOURCES="../../samples/screensaver/logic/logic.c"

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: screensaver[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../../samples/screensaver/logic/logic.dll" -Fo"../../samples/screensaver/logic/" -LD -link %PL_LINKER_FLAGS% -PDB:"../../samples/screensaver/logic/logic_%random%.pdb"

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_screensaver

@del "..\..\samples\screensaver\logic\*.obj"  > nul 2> nul

:Cleanupdebug

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\..\samples\drawfunction3\logic\*.obj"  > nul 2> nul
@del "..\..\samples\mask\logic\*.obj"  > nul 2> nul
@del "..\..\samples\ptz\logic\*.obj"  > nul 2> nul
@del "..\..\samples\screensaver\logic\*.obj"  > nul 2> nul
@del "..\..\samples\functions\logic\*.obj"  > nul 2> nul
@del "..\..\samples\lissajous\logic\*.obj"  > nul 2> nul
@del "..\..\samples\planet\logic\*.obj"  > nul 2> nul
@del "..\..\samples\drawfunction2\logic\*.obj"  > nul 2> nul
@del "..\..\samples\drawfunction1\logic\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../../samples/screensaver/logic/lock.tmp" del "..\..\samples\screensaver\logic\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of debug configuration
goto ExitLabel

:ExitLabel

:: return CWD to previous CWD
@popd
exit /b %PL_BUILD_STATUS%
